apiVersion: v1
kind: Service
metadata:
  labels:
    app: service1
  name: service1-lb
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: service1-http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: service1
  sessionAffinity: None
  type: LoadBalancer